### ISSUE TITLE
Report.tex file does not compile 

### ISSUE THREAD

**Issue by malwaru** [mas-group/project-report#17]
Error Message says : "You have used a command in the main body of your document which should be used in the preamble. Make sure that \documentclass[…]{…} and all \usepackage{…} commands are written before \begin{document}" in **chapters\abstract**

**Comment by alex-mitrevski** [comment]
Hi Malika, what setup do you have and how are you compiling the file? I made some updates to the templates recently, so I know that the current version should compile correctly...

**Comment by malwaru** [comment]
I tried in  in VScode with Tex live latex workshop installed and also in overleaf

**Comment by alex-mitrevski** [comment]
Can you please try compiling from the command line? You can use [this script](https://github.com/mas-group/foundations_course/blob/master/content/latex/latex_tutorial_in_class/article-with-bibliography/compile_latex.bash) for this purpose (where you replace `article` with `report`).

**Comment by malwaru** [comment]
Still get the same error . Checked with a friend even he gets the same error


"! LaTeX Error: Can be used only in preamble.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.2 \begin{document}
                    
? "

**Comment by alex-mitrevski** [comment]
Are you using `\subfile` for including the chapters (as given here in the template) or have you by any chance changed this?

**Comment by malwaru** [comment]
No i did not change anything just cloned the repo and tried to compile it .

**Comment by malwaru** [comment]
Hi Alex , following a friends advice i removed the tags \begin{document} and \end{document} in each sub file. It solved the problem

**Comment by alex-mitrevski** [comment]
That's not actually a solution; there must be another underlying reason why you can't compile the template - maybe some missing packages?

For the record, we use subfiles so that compiling the chapters will also compile the report as a whole.

**Comment by malwaru** [comment]
ok instead of deleting the tags \begin{document} i added the lines \documentclass[../report.tex]{subfiles}
\graphicspath{{\subfix{../images/}}}   . Now it works as well. Is it a better way to do it

**Comment by alex-mitrevski** [comment]
As I suspected, this issue was caused by missing packages. We resolved it by installing `texlive-full`.
